# Generated by Django 4.2.1 on 2023-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timeframe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
