# Generated by Django 4.2.1 on 2023-07-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_pref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
