# Generated by Django 4.2.1 on 2023-09-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0008_remove_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companionship',
        ),
        migrations.AddField(
            model_name='profile',
            name='hunger_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
